"""Add merged_into_id to clusters

Revision ID: 66aacac24eef
Revises: 9b5370ea447a
Create Date: 2025-11-18 16:28:26.017424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66aacac24eef'
down_revision: Union[str, Sequence[str], None] = '9b5370ea447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('merged_into_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_clusters_merged_into_id'), 'clusters', ['merged_into_id'], unique=False)
    op.create_foreign_key(None, 'clusters', 'clusters', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clusters', type_='foreignkey')
    op.drop_index(op.f('ix_clusters_merged_into_id'), table_name='clusters')
    op.drop_column('clusters', 'merged_into_id')
    # ### end Alembic commands ###
