"""add post_id to processed_report

Revision ID: 9b5370ea447a
Revises: ab978b080e2b
Create Date: 2025-11-13 01:52:08.553707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5370ea447a'
down_revision: Union[str, Sequence[str], None] = 'ab978b080e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_reports', sa.Column('post_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_processed_reports_post_id'), 'processed_reports', ['post_id'], unique=False)
    op.create_foreign_key(None, 'processed_reports', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_reports', type_='foreignkey')
    op.drop_index(op.f('ix_processed_reports_post_id'), table_name='processed_reports')
    op.drop_column('processed_reports', 'post_id')
    # ### end Alembic commands ###
