"""Add GIST indexes and pending Foreign Keys

Revision ID: ab978b080e2b
Revises: d31d97f9cbc3
Create Date: 2025-10-31 22:00:55.553104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # <-- ADDED THIS IMPORT


# revision identifiers, used by Alembic.
revision: str = 'ab978b080e2b'
down_revision: Union[str, Sequence[str], None] = 'd31d97f9cbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.create_foreign_key(None, 'clusters', 'posts', ['last_post_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'posts', 'clusters', ['cluster_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'clusters', type_='foreignkey')
    # ### end Alembic commands ###
