"""Create initial tables

Revision ID: d31d97f9cbc3
Revises: 
Create Date: 2025-10-31 21:49:47.468693

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31d97f9cbc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_centroid', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('image_centroid', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('video_centroid', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('avg_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('cluster_radius_meters', sa.Float(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'merged', name='clusterstatusenum'), nullable=False),
    sa.Column('first_report_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_report_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_post_id', sa.Uuid(), nullable=True),
    sa.Column('dominant_category', sa.String(length=100), nullable=True),
    sa.Column('avg_credibility', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_post_id'], ['posts.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_last_report_at'), 'clusters', ['last_report_at'], unique=False)
    op.create_index(op.f('ix_clusters_status'), 'clusters', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('event_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'archived', name='poststatusenum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('parent_post_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], use_alter=True),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_cluster_id'), 'posts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_parent_post_id'), 'posts', ['parent_post_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reputation_score >= 0.0 AND reputation_score <= 1.0', name='check_reputation_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('post_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_type', sa.Enum('upvote', 'downvote', 'flag', name='interactionenum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('flag_reason', sa.Enum('inaccurate', 'spam', 'resolved', 'harmful', name='flagreasonenum'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_interactions_interaction_type'), 'post_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_post_interactions_post_id'), 'post_interactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_interactions_user_id'), 'post_interactions', ['user_id'], unique=False)
    op.create_table('raw_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='reportstatusenum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_reports_status'), 'raw_reports', ['status'], unique=False)
    op.create_index(op.f('ix_raw_reports_user_id'), 'raw_reports', ['user_id'], unique=False)
    op.create_table('processed_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_report_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('event_category', sa.String(length=100), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('avg_spam_score', sa.Float(), nullable=False),
    sa.Column('avg_ai_media_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('report_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_ai_media_score >= 0.0 AND avg_ai_media_score <= 1.0', name='check_ai_range'),
    sa.CheckConstraint('avg_spam_score >= 0.0 AND avg_spam_score <= 1.0', name='check_spam_range'),
    sa.CheckConstraint('consistency_score >= 0.0 AND consistency_score <= 1.0', name='check_consistency_range'),
    sa.CheckConstraint('credibility_score >= 0.0 AND credibility_score <= 1.0', name='check_credibility_range'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['raw_report_id'], ['raw_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_report_id')
    )
    op.create_index(op.f('ix_processed_reports_cluster_id'), 'processed_reports', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_processed_reports_credibility_score'), 'processed_reports', ['credibility_score'], unique=False)
    op.create_index(op.f('ix_processed_reports_event_category'), 'processed_reports', ['event_category'], unique=False)
    op.create_index(op.f('ix_processed_reports_report_created_at'), 'processed_reports', ['report_created_at'], unique=False)
    op.create_index(op.f('ix_processed_reports_user_id'), 'processed_reports', ['user_id'], unique=False)
    op.create_table('raw_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_report_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='mediatypeenum'), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_report_id'], ['raw_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_media_raw_report_id'), 'raw_media', ['raw_report_id'], unique=False)
    op.create_table('post_report_contributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['processed_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_report_contributors_post_id'), 'post_report_contributors', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_report_contributors_report_id'), 'post_report_contributors', ['report_id'], unique=False)
    op.create_table('processed_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processed_report_id', sa.Uuid(), nullable=False),
    sa.Column('raw_media_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='mediatypeenum'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('processed', 'failed_embedding', 'failed_validation', name='processedmediastatusenum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processed_report_id'], ['processed_reports.id'], ),
    sa.ForeignKeyConstraint(['raw_media_id'], ['raw_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_media_processed_report_id'), 'processed_media', ['processed_report_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('processed_media_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['processed_media_id'], ['processed_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_media_processed_media_id'), 'post_media', ['processed_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_media_processed_media_id'), table_name='post_media')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_processed_media_processed_report_id'), table_name='processed_media')
    op.drop_table('processed_media')
    op.drop_index(op.f('ix_post_report_contributors_report_id'), table_name='post_report_contributors')
    op.drop_index(op.f('ix_post_report_contributors_post_id'), table_name='post_report_contributors')
    op.drop_table('post_report_contributors')
    op.drop_index(op.f('ix_raw_media_raw_report_id'), table_name='raw_media')
    op.drop_table('raw_media')
    op.drop_index(op.f('ix_processed_reports_user_id'), table_name='processed_reports')
    op.drop_index(op.f('ix_processed_reports_report_created_at'), table_name='processed_reports')
    op.drop_index(op.f('ix_processed_reports_event_category'), table_name='processed_reports')
    op.drop_index(op.f('ix_processed_reports_credibility_score'), table_name='processed_reports')
    op.drop_index(op.f('ix_processed_reports_cluster_id'), table_name='processed_reports')
    op.drop_table('processed_reports')
    op.drop_index(op.f('ix_raw_reports_user_id'), table_name='raw_reports')
    op.drop_index(op.f('ix_raw_reports_status'), table_name='raw_reports')
    op.drop_table('raw_reports')
    op.drop_index(op.f('ix_post_interactions_user_id'), table_name='post_interactions')
    op.drop_index(op.f('ix_post_interactions_post_id'), table_name='post_interactions')
    op.drop_index(op.f('ix_post_interactions_interaction_type'), table_name='post_interactions')
    op.drop_table('post_interactions')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_posts_parent_post_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_cluster_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_clusters_status'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_last_report_at'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
